//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace CodaService.OcsBeeline {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServicesSoap", Namespace="http://www.services.laotel.com")]
    public partial class Services : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback queryBalanceOperationCompleted;
        
        private System.Threading.SendOrPostCallback cashRecharegeOperationCompleted;
        
        private System.Threading.SendOrPostCallback adjustBalanceOperationCompleted;
        
        private System.Threading.SendOrPostCallback voucherRechargeOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Services() {
            this.Url = global::CodaService.Properties.Settings.Default.CodaService_OcsBeeline_Services;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event queryBalanceCompletedEventHandler queryBalanceCompleted;
        
        /// <remarks/>
        public event cashRecharegeCompletedEventHandler cashRecharegeCompleted;
        
        /// <remarks/>
        public event adjustBalanceCompletedEventHandler adjustBalanceCompleted;
        
        /// <remarks/>
        public event voucherRechargeCompletedEventHandler voucherRechargeCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.services.laotel.com/queryBalance", RequestNamespace="http://www.services.laotel.com", ResponseNamespace="http://www.services.laotel.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public queryBalanceResult queryBalance(queryBalanceRequest msg) {
            object[] results = this.Invoke("queryBalance", new object[] {
                        msg});
            return ((queryBalanceResult)(results[0]));
        }
        
        /// <remarks/>
        public void queryBalanceAsync(queryBalanceRequest msg) {
            this.queryBalanceAsync(msg, null);
        }
        
        /// <remarks/>
        public void queryBalanceAsync(queryBalanceRequest msg, object userState) {
            if ((this.queryBalanceOperationCompleted == null)) {
                this.queryBalanceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnqueryBalanceOperationCompleted);
            }
            this.InvokeAsync("queryBalance", new object[] {
                        msg}, this.queryBalanceOperationCompleted, userState);
        }
        
        private void OnqueryBalanceOperationCompleted(object arg) {
            if ((this.queryBalanceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.queryBalanceCompleted(this, new queryBalanceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.services.laotel.com/cashRecharege", RequestNamespace="http://www.services.laotel.com", ResponseNamespace="http://www.services.laotel.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public paymentResult cashRecharege(paymentRequest msg) {
            object[] results = this.Invoke("cashRecharege", new object[] {
                        msg});
            return ((paymentResult)(results[0]));
        }
        
        /// <remarks/>
        public void cashRecharegeAsync(paymentRequest msg) {
            this.cashRecharegeAsync(msg, null);
        }
        
        /// <remarks/>
        public void cashRecharegeAsync(paymentRequest msg, object userState) {
            if ((this.cashRecharegeOperationCompleted == null)) {
                this.cashRecharegeOperationCompleted = new System.Threading.SendOrPostCallback(this.OncashRecharegeOperationCompleted);
            }
            this.InvokeAsync("cashRecharege", new object[] {
                        msg}, this.cashRecharegeOperationCompleted, userState);
        }
        
        private void OncashRecharegeOperationCompleted(object arg) {
            if ((this.cashRecharegeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.cashRecharegeCompleted(this, new cashRecharegeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.services.laotel.com/adjustBalance", RequestNamespace="http://www.services.laotel.com", ResponseNamespace="http://www.services.laotel.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public adjustBalanceResult adjustBalance(adjustBalanceRequest msg) {
            object[] results = this.Invoke("adjustBalance", new object[] {
                        msg});
            return ((adjustBalanceResult)(results[0]));
        }
        
        /// <remarks/>
        public void adjustBalanceAsync(adjustBalanceRequest msg) {
            this.adjustBalanceAsync(msg, null);
        }
        
        /// <remarks/>
        public void adjustBalanceAsync(adjustBalanceRequest msg, object userState) {
            if ((this.adjustBalanceOperationCompleted == null)) {
                this.adjustBalanceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnadjustBalanceOperationCompleted);
            }
            this.InvokeAsync("adjustBalance", new object[] {
                        msg}, this.adjustBalanceOperationCompleted, userState);
        }
        
        private void OnadjustBalanceOperationCompleted(object arg) {
            if ((this.adjustBalanceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.adjustBalanceCompleted(this, new adjustBalanceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.services.laotel.com/voucherRecharge", RequestNamespace="http://www.services.laotel.com", ResponseNamespace="http://www.services.laotel.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public voucherRechargeResult voucherRecharge(voucherRechargeRequest msg) {
            object[] results = this.Invoke("voucherRecharge", new object[] {
                        msg});
            return ((voucherRechargeResult)(results[0]));
        }
        
        /// <remarks/>
        public void voucherRechargeAsync(voucherRechargeRequest msg) {
            this.voucherRechargeAsync(msg, null);
        }
        
        /// <remarks/>
        public void voucherRechargeAsync(voucherRechargeRequest msg, object userState) {
            if ((this.voucherRechargeOperationCompleted == null)) {
                this.voucherRechargeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnvoucherRechargeOperationCompleted);
            }
            this.InvokeAsync("voucherRecharge", new object[] {
                        msg}, this.voucherRechargeOperationCompleted, userState);
        }
        
        private void OnvoucherRechargeOperationCompleted(object arg) {
            if ((this.voucherRechargeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.voucherRechargeCompleted(this, new voucherRechargeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.services.laotel.com")]
    public partial class queryBalanceRequest {
        
        private headerRequest headerField;
        
        private string msisdnField;
        
        /// <remarks/>
        public headerRequest header {
            get {
                return this.headerField;
            }
            set {
                this.headerField = value;
            }
        }
        
        /// <remarks/>
        public string msisdn {
            get {
                return this.msisdnField;
            }
            set {
                this.msisdnField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.services.laotel.com")]
    public partial class headerRequest {
        
        private string useridField;
        
        private string passwordField;
        
        private string chanelField;
        
        private string trans_idField;
        
        /// <remarks/>
        public string userid {
            get {
                return this.useridField;
            }
            set {
                this.useridField = value;
            }
        }
        
        /// <remarks/>
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        public string chanel {
            get {
                return this.chanelField;
            }
            set {
                this.chanelField = value;
            }
        }
        
        /// <remarks/>
        public string trans_id {
            get {
                return this.trans_idField;
            }
            set {
                this.trans_idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.services.laotel.com")]
    public partial class voucherRechargeResult {
        
        private headerResult headerField;
        
        private long newBalanceField;
        
        private string newActiveStopField;
        
        private int validityPeriodField;
        
        private int extraValidityField;
        
        /// <remarks/>
        public headerResult header {
            get {
                return this.headerField;
            }
            set {
                this.headerField = value;
            }
        }
        
        /// <remarks/>
        public long newBalance {
            get {
                return this.newBalanceField;
            }
            set {
                this.newBalanceField = value;
            }
        }
        
        /// <remarks/>
        public string newActiveStop {
            get {
                return this.newActiveStopField;
            }
            set {
                this.newActiveStopField = value;
            }
        }
        
        /// <remarks/>
        public int validityPeriod {
            get {
                return this.validityPeriodField;
            }
            set {
                this.validityPeriodField = value;
            }
        }
        
        /// <remarks/>
        public int extraValidity {
            get {
                return this.extraValidityField;
            }
            set {
                this.extraValidityField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.services.laotel.com")]
    public partial class headerResult {
        
        private string resultCodeField;
        
        private string resultDescField;
        
        private string trans_idField;
        
        /// <remarks/>
        public string resultCode {
            get {
                return this.resultCodeField;
            }
            set {
                this.resultCodeField = value;
            }
        }
        
        /// <remarks/>
        public string resultDesc {
            get {
                return this.resultDescField;
            }
            set {
                this.resultDescField = value;
            }
        }
        
        /// <remarks/>
        public string trans_id {
            get {
                return this.trans_idField;
            }
            set {
                this.trans_idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.services.laotel.com")]
    public partial class voucherRechargeRequest {
        
        private headerRequest headerField;
        
        private string msisdnField;
        
        private string pinField;
        
        /// <remarks/>
        public headerRequest header {
            get {
                return this.headerField;
            }
            set {
                this.headerField = value;
            }
        }
        
        /// <remarks/>
        public string msisdn {
            get {
                return this.msisdnField;
            }
            set {
                this.msisdnField = value;
            }
        }
        
        /// <remarks/>
        public string pin {
            get {
                return this.pinField;
            }
            set {
                this.pinField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.services.laotel.com")]
    public partial class adjustBalanceResult {
        
        private headerResult headerField;
        
        private balanceDetail[] balanceDetailField;
        
        /// <remarks/>
        public headerResult header {
            get {
                return this.headerField;
            }
            set {
                this.headerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public balanceDetail[] balanceDetail {
            get {
                return this.balanceDetailField;
            }
            set {
                this.balanceDetailField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.services.laotel.com")]
    public partial class balanceDetail {
        
        private string balanceNameField;
        
        private string balanceTypeField;
        
        private long balanceField;
        
        private string expireField;
        
        /// <remarks/>
        public string balanceName {
            get {
                return this.balanceNameField;
            }
            set {
                this.balanceNameField = value;
            }
        }
        
        /// <remarks/>
        public string balanceType {
            get {
                return this.balanceTypeField;
            }
            set {
                this.balanceTypeField = value;
            }
        }
        
        /// <remarks/>
        public long balance {
            get {
                return this.balanceField;
            }
            set {
                this.balanceField = value;
            }
        }
        
        /// <remarks/>
        public string expire {
            get {
                return this.expireField;
            }
            set {
                this.expireField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.services.laotel.com")]
    public partial class adjustBalanceRequest {
        
        private headerRequest headerField;
        
        private string msisdnField;
        
        private long amountField;
        
        private int typeField;
        
        /// <remarks/>
        public headerRequest header {
            get {
                return this.headerField;
            }
            set {
                this.headerField = value;
            }
        }
        
        /// <remarks/>
        public string msisdn {
            get {
                return this.msisdnField;
            }
            set {
                this.msisdnField = value;
            }
        }
        
        /// <remarks/>
        public long amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
            }
        }
        
        /// <remarks/>
        public int type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.services.laotel.com")]
    public partial class paymentResult {
        
        private headerResult headerField;
        
        private long newBalanceField;
        
        private string newActiveStopField;
        
        private int validityPeriodField;
        
        private int extraValidityField;
        
        /// <remarks/>
        public headerResult header {
            get {
                return this.headerField;
            }
            set {
                this.headerField = value;
            }
        }
        
        /// <remarks/>
        public long newBalance {
            get {
                return this.newBalanceField;
            }
            set {
                this.newBalanceField = value;
            }
        }
        
        /// <remarks/>
        public string newActiveStop {
            get {
                return this.newActiveStopField;
            }
            set {
                this.newActiveStopField = value;
            }
        }
        
        /// <remarks/>
        public int validityPeriod {
            get {
                return this.validityPeriodField;
            }
            set {
                this.validityPeriodField = value;
            }
        }
        
        /// <remarks/>
        public int extraValidity {
            get {
                return this.extraValidityField;
            }
            set {
                this.extraValidityField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.services.laotel.com")]
    public partial class paymentRequest {
        
        private headerRequest headerField;
        
        private string msisdnField;
        
        private string pinField;
        
        private long amountField;
        
        /// <remarks/>
        public headerRequest header {
            get {
                return this.headerField;
            }
            set {
                this.headerField = value;
            }
        }
        
        /// <remarks/>
        public string msisdn {
            get {
                return this.msisdnField;
            }
            set {
                this.msisdnField = value;
            }
        }
        
        /// <remarks/>
        public string pin {
            get {
                return this.pinField;
            }
            set {
                this.pinField = value;
            }
        }
        
        /// <remarks/>
        public long amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.services.laotel.com")]
    public partial class queryBalanceResult {
        
        private headerResult headerField;
        
        private balanceDetail[] balanceDetailField;
        
        /// <remarks/>
        public headerResult header {
            get {
                return this.headerField;
            }
            set {
                this.headerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public balanceDetail[] balanceDetail {
            get {
                return this.balanceDetailField;
            }
            set {
                this.balanceDetailField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void queryBalanceCompletedEventHandler(object sender, queryBalanceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class queryBalanceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal queryBalanceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public queryBalanceResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((queryBalanceResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void cashRecharegeCompletedEventHandler(object sender, cashRecharegeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class cashRecharegeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal cashRecharegeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public paymentResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((paymentResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void adjustBalanceCompletedEventHandler(object sender, adjustBalanceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class adjustBalanceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal adjustBalanceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public adjustBalanceResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((adjustBalanceResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void voucherRechargeCompletedEventHandler(object sender, voucherRechargeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class voucherRechargeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal voucherRechargeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public voucherRechargeResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((voucherRechargeResult)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591