//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodaService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_request_log
    {
        public long id { get; set; }
        public string msisdn { get; set; }
        public string gameName { get; set; }
        public string cardType { get; set; }
        public Nullable<int> paidAmount { get; set; }
        public string resultCode { get; set; }
        public string resultDesc { get; set; }
        public Nullable<System.DateTime> resultDate { get; set; }
    }
}
