//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodaService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_header
    {
        public int ID { get; set; }
        public string HeaderName { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> StopDate { get; set; }
        public string Company { get; set; }
        public string Username { get; set; }
        public Nullable<int> ReqID { get; set; }
        public Nullable<int> ReqIDUAT { get; set; }
        public string Type { get; set; }
        public Nullable<bool> Mmoney { get; set; }
        public string userid { get; set; }
        public string password { get; set; }
        public string userUAT { get; set; }
        public string passUAT { get; set; }
        public Nullable<bool> IsLTC { get; set; }
        public Nullable<bool> IsTPlus { get; set; }
        public string HeaderCode { get; set; }
        public string USSDCode { get; set; }
    }
}
