//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodaService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_deduct_log
    {
        public long id { get; set; }
        public string transactionID { get; set; }
        public string msisdn { get; set; }
        public Nullable<long> amount { get; set; }
        public string gameName { get; set; }
        public string cardType { get; set; }
        public Nullable<System.DateTime> deductDate { get; set; }
        public string username { get; set; }
        public string resultCode { get; set; }
        public string resultDesc { get; set; }
        public string ocsCode { get; set; }
        public string ocsDesc { get; set; }
        public Nullable<int> newBalance { get; set; }
        public Nullable<int> oldBalance { get; set; }
        public string smsStatus { get; set; }
        public string email { get; set; }
        public string ip { get; set; }
        public string @operator { get; set; }
    }
}
