//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodaService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_sms_log
    {
        public long id { get; set; }
        public string msisdn { get; set; }
        public string message { get; set; }
        public Nullable<System.DateTime> send_date { get; set; }
        public string email { get; set; }
        public string resultCode { get; set; }
        public string resultDesc { get; set; }
    }
}
