//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodaService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_request_log_production
    {
        public long ID { get; set; }
        public string TransactionID { get; set; }
        public string Msisdn { get; set; }
        public Nullable<int> PaidAmount { get; set; }
        public string ResultCode { get; set; }
        public string ResultDesc { get; set; }
        public Nullable<System.DateTime> ResultDate { get; set; }
        public string UserName { get; set; }
        public string RequestType { get; set; }
        public string OTP { get; set; }
        public Nullable<bool> OTPStatus { get; set; }
        public string RefCode { get; set; }
        public string Operator { get; set; }
        public Nullable<bool> Status { get; set; }
        public string ServiceType { get; set; }
    }
}
