//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodaService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_confirm_deduct
    {
        public long Id { get; set; }
        public string TransactionID { get; set; }
        public string RefCode { get; set; }
        public string Msisdn { get; set; }
        public string Gamename { get; set; }
        public string Cardname { get; set; }
        public Nullable<System.DateTime> DeductDate { get; set; }
        public string ResultCode { get; set; }
        public string ResultDesc { get; set; }
        public Nullable<int> OldBalance { get; set; }
        public Nullable<int> NewBalance { get; set; }
        public Nullable<bool> SMSStatus { get; set; }
        public string Operator { get; set; }
        public string DeductType { get; set; }
        public string IPAddress { get; set; }
        public string Email { get; set; }
        public string Username { get; set; }
        public string RequestType { get; set; }
        public Nullable<int> Amount { get; set; }
    }
}
