//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodaService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_backlist
    {
        public int ID { get; set; }
        public string Msisdn { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string ResultCode { get; set; }
        public string ResultDesc { get; set; }
        public Nullable<bool> Status { get; set; }
    }
}
