//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodaService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_member
    {
        public int Id { get; set; }
        public string Msisdn { get; set; }
        public Nullable<System.DateTime> RegisterDate { get; set; }
        public Nullable<bool> Status { get; set; }
        public string ResultCode { get; set; }
        public string ResultDesc { get; set; }
        public string GameName { get; set; }
        public string Username { get; set; }
        public string Operator { get; set; }
        public string Header { get; set; }
        public Nullable<System.DateTime> CancelDate { get; set; }
    }
}
